blank_issues_enabled: false
contact_links:
  - name: Herd Pro
    url: https://beyondcode.com
    about: 'For license and billing related questions, please send us an email to support@beyondco.de'
  - name: Feature request
    url: https://github.com/beyondcode/herd-community/discussions
    about: 'For ideas or feature requests, start a new discussion'
  - name: Check the docs
    url: https://herd.laravel.com/docs
    about: "This repository is for reporting bugs and proposing new features. If you need help with your first steps with Herd, check out the docs!"
  - name: Security vulnerabilities
    url: https://beyondcode.com
    about: If you want to report a security issue, please contact our support.
