name: 'Close stale issues and PRs'
on:
  workflow_dispatch
#  schedule:
#    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          only-labels: 'needs more information'
          debug-only: true
          days-before-stale: 5
          days-before-close: 7
          
          
